import blackTee from '../assets/blacktee.jpg';
import whiteTee from '../assets/whiteTee.jpg';
const data = [
  {
    id: 1,
    title: 'ZAIMEH SHIRT',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: blackTee,
  },
  {
    id: 2,
    title: 'Trendy Tall Tee',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 3,
    title: 'LJ&S Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: blackTee,
  },
  {
    id: 4,
    title: 'Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 5,
    title: 'LJ&S  Tall Tee',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: blackTee,
  },
  {
    id: 10,
    title: 'LJ&S Heavyweight Relaxed-Fit Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 6,
    title: 'LJ&S Heavyweight Relaxed-Fit Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 7,
    title: 'LJ&S Heavyweight Relaxed-Fit Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 8,
    title: 'LJ&S Heavyweight Relaxed-Fit Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
  {
    id: 9,
    title: 'LJ&S Heavyweight Relaxed-Fit Tall Tee in Sumac',
    description: 'A relaxed-fit, heavyweight tee made from premium fabric in Sumac.',
    price: 19900,
    colors: [
      { name: 'Sumac Black', hexCode: '#000000', image: blackTee },
      { name: 'Sumac Navy', hexCode: '#1c4d8c', image: whiteTee },
      { name: 'Sumac White', hexCode: '#f5f5f5', image: whiteTee },
      { name: 'Sumac Gray', hexCode: '#8e8e8e', image: blackTee },
      { name: 'Sumac Red', hexCode: '#7b0f18', image: whiteTee },
    ],
    colorOptions: ['#000000', '#1c4d8c', '#f5f5f5', '#8e8e8e', '#7b0f18'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    image: whiteTee,
  },
];

export default data;
